### ISSUE TITLE
ThreadsService and others missing OpenAI-Beta=assistants=v1 http header

### ISSUE THREAD

**Issue by sevzas** [JZO001/Forge.OpenAI#10]
This line appears in AssistantService:

_apiHttpService.DefaultRequestHeaders.Add("OpenAI-Beta", "assistants=v1");

based on the curl examples on the OpenAi web site, such as https://platform.openai.com/docs/api-reference/threads it appears that the following services also need this line: ThreadsService, MessageService, RunService and RunStepService.

I suspect that this missing line is the cause of me seeing this error message while trying to call RunSvc.CreateThreadAndRunAsync(runRequest).Result

{
  "error": {
    "type": "invalid_request_error",
    "code": "unknown_url",
    "message": "Unknown request URL: POST /threads/runs. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.",
    "param": null
  }
}

**Comment by JZO001** [comment]
Interesting, the playground examples worked without that. I will check in the evening what was changed on OpenAI side.

**Comment by JZO001** [comment]
I need a bit more time to solve this issue

**Comment by sevzas** [comment]
Thanks for the update... Looking forward to a resolution.

**Comment by JZO001** [comment]
Fixed in v1.3.3

**Comment by JZO001** [comment]
Thanks for the feedback! I fixed the issue and released v1.3.4.

**Comment by sevzas** [comment]
I appreciate your timely fixes...

looks like there is (at least) one bug remaining in RunService.CreateThreadAndRunAsync():

When you call _apiHttpService.PostAsync on line 91, the first parameter "_options.RunThreadAndRunCreateUri" is incorrect because it is missing the "/v1/" segment that all of the other invocations of _apiHttpService.PostAsync have.  This is because the first parameter's value is built with GetXXXXXXXUri() in all of the other places.

**Comment by JZO001** [comment]
Thank you, I am really appreciate to help me to test the SDK. I fixed this URL issue and released a new one.

**Comment by sevzas** [comment]
I am now able to send a request using RunService.CreateThreadAndRunAsync() .  Thank you.
