### ISSUE TITLE
Properties missing from RunResponse class

### ISSUE THREAD

**Issue by sevzas** [JZO001/Forge.OpenAI#11]
As best as I can understand, the intention of the RunSvc.GetAsync(ThreadId, RunId) is to retrieve the details for a single Run.

I believe that this method corresponds to this OpenAI API call: https://platform.openai.com/docs/api-reference/runs/getRun

I see the response is contained in the RunResponse class, but the RunResponse class is missing the actual properties of the Run that I'm looking to read such as "status".

Can you add them?

**Comment by JZO001** [comment]
Thanks for your feedback! I added the missing properties to the response class. v.1.3.6 released.

**Comment by sevzas** [comment]
looks good.  Thank you.  Closing...
