### ISSUE TITLE
   RunService and RunStepService members not being initialized in the 2nd constructor of OpenAIService

### ISSUE THREAD

**Issue by sevzas** [JZO001/Forge.OpenAI#9]
In the 2nd constructor of OpenAIService, the one with this signature:

public OpenAIService(OpenAIOptions options, IApiHttpService apiHttpService, IProviderEndpointService providerEndpointService)

the RunService and RunStepService members are not being initialized and they remain null.  Looks like maybe Zoltan forgot to add initialization for these two members when he added it to the first constructor?

**Comment by JZO001** [comment]
Hello,
Its confirmed. Ths fixed is released in v1.3.2.

Thank you for your feedback.

**Comment by sevzas** [comment]
Looks good, thank you for the quick response.

**Comment by sevzas** [comment]
Closing...
